// Generated by CoffeeScript 1.10.0
(function() {
  Polymer({
    is: "qr-code",
    properties: {
      _computedURI: {
        computed: "_computeURI(backgroundColor, color, data, ecc, _computedSize)"
      },
      _computedSize: {
        computed: "_computeSize(height, width)"
      },
      backgroundColor: {
        type: String,
        value: "ffffff"
      },
      color: {
        type: String,
        value: "000000"
      },
      data: {
        type: String,
        value: ""
      },
      ecc: {
        type: String,
        value: "L"
      },
      height: {
        type: Number,
        value: 200
      },
      width: {
        type: Number,
        value: 200
      }
    },
    _computeSize: function(height, width) {
      var side;
      side = height > width ? height : width;
      return side + "x" + side;
    },
    _computeURI: function(backgroundColor, color, data, ecc, _computedSize) {
      return "//api.qrserver.com/v1/create-qr-code/?bgcolor=" + backgroundColor + "&color=" + color + "&data=" + data + "&ecc=" + ecc + "&size=" + _computedSize;
    }
  });

}).call(this);

//# sourceMappingURL=qr-code.js.map
